version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: LivrariaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "1917:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/LivrariaDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
